### ISSUE TITLE
アンチハラスメントポリシーのページを作成する

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk06#14]

**Comment by yoshiokaCB** [comment]
これってオープンソースでしたっけ？
どこかでチラッとそんな記述を見た気がしますが。。。
http://matsue.rubyist.net/matrk06/

利用できるなら必要な箇所を修正して利用したいですね。

**Comment by sho-h** [comment]
(たかおさん、まだやるつもりなのかがちょっと気になるところですが)
CCあたりじゃないかと思ったのですが、見つけられませんでした。

**Comment by yoshiokaCB** [comment]
了解です！ありがとうございます！
また土曜のMatsue.rbの時にでも相談させてください。

**Comment by yoshiokaCB** [comment]
当日口答で注意します。
講演者にはあらかじめ注意を喚起しておきます。
