### ISSUE TITLE
ライブコーディング大喜利のページを作成する

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk06#15]

**Comment by inoh** [comment]
@yoshiokaCB さん
ホームページ上のライブコーディング大喜利の内容についてどうしましょうか。
前の話だと当日説明用にページを作るとのことでしたが載せる内容について少しつめが必要に思いました。
載せる内容候補はこんな感じですかね？
- 問題を出題する流れ
- 出演者
- 出題する問題
- 問題に対する例題

**Comment by yoshiokaCB** [comment]
@inoh さん

載せる内容は以下のもので良いと思います。
- 問題を出題する流れ
- 出演者
- 出題する問題

「問題に対する例題」は回答がかぶっても困るので、なしの方向にしようかと（汗）

色々とありがとうございます！

**Comment by inoh** [comment]
了解です！
では上記の３点でとりあえずページ作ります。

**Comment by inoh** [comment]
@yoshiokaCB さん
ライブコーディング大喜利のページを作成しました。
https://github.com/matsuerb/matsuerb-nanoc/pull/214
出演者についてはプログラムのところに載せています。
確認お願いします！

**Comment by sho-h** [comment]
あ、マージしてしまいました...
http://matsue.rubyist.net/matrk06

**Comment by inoh** [comment]
ありがとうございます！
また気になる点があれば改めてプルリク送らせてもらいます。

**Comment by inoh** [comment]
そういえば大喜利の流れですが

**修正前**  

<pre>
1. 司会者がお題を提示
2. 回答者手を挙げる
3. 回答者へモニタを切り替える
4. 回答者がコードを書く
5. コードが動くことを確認
6. 2へ戻る（数回繰り返す）
</pre>

2と4を入れ替える感じで

**修正後**

<pre>
1. 司会者がお題を提示
2. 回答者がコードを書く
3. 回答者手を挙げる
4. 回答者へモニタを切り替える
5. コードが動くことを確認
6. 2へ戻る（数回繰り返す）
</pre>

みたいな感じで修正したほうがよいですか？

**Comment by yoshiokaCB** [comment]
@inoh さん
修正後に変更してもらえると助かります。
ただ、当日までにさらに変更が加わるかもしれないで、最後に以下の一文を追加してください。

<pre>
注）流れに関しては多少の変更が発生するかもしれません。
</pre>

**Comment by inoh** [comment]
了解です！
とりあえず上記の内容については修正しました。
@sho-h さん
プルリクしたので反映お願いします！

**Comment by sho-h** [comment]
反映しましたー。

**Comment by inoh** [comment]
ありがとうございます！
