### ISSUE TITLE
doorkeeperに参加登録と懇親会のイベントを作成する

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk06#16]

**Comment by Takashi-U** [comment]
下記Issueと被ってる部分があるので、こちらを生かして、下記IssueをCloseとしておきます。
※Issueの内容をコピペしておきます。

https://github.com/matsuerb/matrk06/issues/11

## DoorKeeperで受付ページを作る
- 定員30名（当初お店には30名で予約。お店と確認しながら適宜調整。）
- 18時〜
- 松江テルサ中会議室
- 会費4,000円
- 締め切りは仮に12/12（お店と確認しながら適宜後ろへ）

**Comment by inoh** [comment]
@Takashi-U 
もろもろありがとうございます！
とりあえずのイベント登録をdoorkeeperに作成しました。
**参加登録**
http://matsue-rb.doorkeeper.jp/events/16078
**懇親会**
http://matsue-rb.doorkeeper.jp/events/16079
まだ一般公開はしていないのでdoorkeeperの松江Ruby会議のコミュニティに入っている人だけ確認できるかもです。

**Comment by amidaku** [comment]
DoorKeeperの非公開イベントは、管理者のみ見ることができます。コミュニティー参加者が見れると、非公開にならないのでw
関係者に確認が必要なら、画面キャプチャして共有するのが良いと思いますよ。
ではー

**Comment by inoh** [comment]
とりあえず内容は前回のをコピーしてあまり詰めてないですが現状かける範囲でとりあえずイベント作ってます。
PDFで共有してあるので現状下記のPDFを参考にしてください。

**イベント登録**
https://drive.google.com/file/d/0BwbhUrybRgO4MTBOeEZndnc2Z00/view?usp=sharing

**懇親会登録**
https://drive.google.com/file/d/0BwbhUrybRgO4Yi1KcTdQMGJOZDg/view?usp=sharing

**Comment by inoh** [comment]
ちなみに気になる点を補足です。

**当日来場者の写真撮影について**
以前の打ち合わせの中で写真班から来場者の写真撮影有無について確認が必要かという話がありました。
Doorkeeperで同意のチェックをするための機能が見当たらなかったのでとりあえず断りの文章を入れました。

**懇親会の時間帯**
懇親会の開催時間は18:00 から 20:00 としています。
スタート時間は18時でよいという認識ですが終わりの時間は20時でよいですかね？もしくは書かない方がよい？

**Comment by amidaku** [comment]
作成お疲れ様です。
写真撮影同意の記載はとても良いと思います。
出来れば同意いただく気持ちを強めた文字の方が良いと感じました。
例えば、
「イベント終了後に開催の様子を多くの方にご覧頂くために、当日は写真撮影をいたします。ご理解をお願いいたします。」
とかそういう文字の方が良いかなと感じました。

**Comment by inoh** [comment]
ご指摘ありがとうございます。
こういった文章を書くのが不慣れなものでアドバイスいただけると大変助かります。
参考に修正します。

**Comment by inoh** [comment]
@amidaku さんの文言そのままですがdoorkeeperの内容を修正してPDFを置き換えました。
@yoshiokaCB さん
また公開時期とかあれば指示いたければ公開します。

**Comment by yoshiokaCB** [comment]
@inoh さん

作業ありがとうございます！

> イベント登録
> https://drive.google.com/file/d/0BwbhUrybRgO4MTBOeEZndnc2Z00/view?usp=sharing

サイトへのリンクがあった方が良いと思いますがどんなもんでしょうか？
相談済で見落としてたらごめんなさい。
リンク先:
http://matsue.rubyist.net/matrk06/

> 懇親会登録
> https://drive.google.com/file/d/0BwbhUrybRgO4Yi1KcTdQMGJOZDg/view?usp=sharing

@Takashi-U 
懇親会の費用って、4,000円でよかったっけ？
あと学生の料金って決めてなかったよね。どうしましょう？

**Comment by inoh** [comment]
> サイトへのリンクがあった方が良いと思いますがどんなもんでしょうか？

詳細情報としてリンク追加しておきました！

**Comment by Takashi-U** [comment]
@yoshiokaCB 
懇親会の費用については、4,000円が下限ということの確認でストップしてます。失礼しました。
現況、一般の方には500円アップをお願いする案と、 @ToruKurahashi さんのアイデアがありまして、そこの所加味して、当方が交渉してみるということでいかがでしょうか？
学生の方達の金額がどれほどが妥当か、こちらが想定している額で妥結できるか…という心配はありますが。。

**Comment by yoshiokaCB** [comment]
@inoh さん
変更確認しました。ありがとうございます！
松江Ruby会議の申し込みは再来週にMatsue.rbがあるので、そのタイミングくらいで公開したいと思います。懇親会はもうしばらくお待ち下さい。

@Takashi-U 
こっちこそ投げっぱなしでごめんなさい。交渉おまかせします！
なんか相談や判断が必要なことがあったら言ってください。（懇親会費用は4,500円でもいいと思いますよ。）
んで、金額決まったら @inoh さんに伝えてください。
学生は2,000円〜2,500円くらいって話だったっけ？来てくれそうな学生に今度聞いときましょうか？

**Comment by Takashi-U** [comment]
@yoshiokaCB 
カプリチョーザさんにお願い電話してみました。
ノンアルコールの学生さん（学生証提示）については3,000円、その他の人は3,500円という事にまとまりました。

その他の人は4,000円で徴収させていただいて、学生さんについては2,000円とすると、3人中1人が学生という状況でも対応できます。

このような状況から、私個人としてはアルコールの学生さんの事や、ある程度の余裕をもってと考え、一般の方には申し訳無いですが4,500円をお願いするというのを、第一の候補と考えましたがいかがでしょうか？
（多めに設定して、余れば少なくするというのが吉かと。。）

いろいろな組み合わせが考えられるところでございます。他のアイデアもあればバシバシお願いします。
ご検討下さいませ。（数日程度で結論をだして募集開始したいですね。丸2ヶ月程度募集できたらOKかなと。）

**Comment by yoshiokaCB** [comment]
なるほど。
学生2,000円で良いと思いますよ。
可能ならノンアルコールの人の料金を下げてあげたいけど、どんな感じかな？（ノンアルコールの人は3,500とか）
それと、県外からのゲスト（コーダーと講演者）が二人ほど来られる予定です。
なので二人分を余分に計算してもらえると助かります。

今のところ基本的には4,500円の線で考えたいですね。

**Comment by inoh** [comment]
とりあえず現状でdoorkeeperを修正しました。
https://drive.google.com/file/d/0BwbhUrybRgO4Yi1KcTdQMGJOZDg/view
またアルコールの有無で値段設定を変える場合は修正します。

**Comment by yoshiokaCB** [comment]
@inoh さん
確認しました！ありがとうございます。

@Takashi-U 
値段設定どうしましょ？　誰と誰に確認とっておけばOK？　（誰を巻き込む？）

**Comment by Takashi-U** [comment]
@yoshiokaCB さん
できたら土曜日におめにかかって最終的に決定したいと思います。いかがでしょうか？
というのも、参加人数や学生の割合等によって、最終的な価格が結果的に変わってくる可能性があり、予め場合によっての方針を決めたいなと思った次第です。

確認については、@yoshiokaCB さんが決定した事については異論が出ないと思いますので、抜けが無いか念のため数人に「これでいきますわー」とレビュー依頼する程度で良いと思っています。

よろしくです。。

**Comment by yoshiokaCB** [comment]
@Takashi-U 
了解っす。では土曜日に話しましょう！

**Comment by yoshiokaCB** [comment]
@inoh さん
本編はOKです！
公開しちゃってください！！
懇親会は料金設定をちょっと変更しますので、少々お待ちください。

@Takashi-U 
学生の料金設定だけど高尾さんから「チケット数を制限したらどうか」というアドバイスがありました。今の料金設定で学生は何人までなら割引対象にできるかざっと計算は出来るかな？
（一般25人くらいで計算したっけ？）

**Comment by Takashi-U** [comment]
@yoshiokaCB さん
取り急ぎ、、
学生は4人までなら割引対象にできる計算です。一般25人として計算しています。
昨日のお話では万一余ったり不足したりしたらという前提でしたので、計画通りに行けば上記の人数となります。

**Comment by inoh** [comment]
@yoshiokaCB 
講演のエントリ開始しました！

@sho-h 
ホームページについても修正を行いました！
たびたびお願いして申し訳ありませんが反映お願いします！
https://github.com/matsuerb/matsuerb-nanoc/pull/205

**Comment by Takashi-U** [comment]
@yoshiokaCB さん
価格設定を変更するならアレですが、人数の増減に対応するだけであれば、 @inoh さんにお願いしても良い段階かと思いますがいかがでしょうか？

現在のところ、
- 一般会費 4,500円
- 一般会費（ノンアルコール） 4,000円
- 学生 2,500円
- 学生（ノンアルコール）2,000円
  ※学生枠は4名

ということになっております。
ご確認の程よろしくお願いいたします。

**Comment by sho-h** [comment]
@inoh さん、ありがとうございます！マージと反映をしましたー。

**Comment by yoshiokaCB** [comment]
@inoh さん @sho-h さん
ありがとうございます。

@Takashi-U 
了解っす。
では @inoh さん 以下の料金設定に変更して公開をお願いします。

> - 一般会費 4,500円
> - 一般会費（ノンアルコール） 4,000円
> - 学生 2,500円
> - 学生（ノンアルコール）2,000円 ※学生枠は4名

とりあえず、学生の枠は各2人にしておきましょうか。

**Comment by inoh** [comment]
@yoshiokaCB さん @Takashi-U さん
とりあえず懇親会のdoorkeeperを公開しました。
http://matsue-rb.doorkeeper.jp/events/16079
学生枠の人数制限ですがdoorkeeperでチケットごとに人数制限ができなかったのでとりあえず断りの文言を入れておきました。
例年だとどれくらい学生のエントリがあったんでしょうか。
もし多いようでしたら予算オーバーも怖いのでエントリ自体を分ける必要があるかもです。

@sho-h さん 
ホームページの修正を行いました！またまた反映お願いします！
https://github.com/matsuerb/matsuerb-nanoc/pull/206

**Comment by Takashi-U** [comment]
@inoh さん、ありがとうございます！

学生の件ですが、現状ですと当日にならないと学生が何人かわからない事になると思います。ですので、inohさんご指摘の「エントリ自体を分ける」あるいは「学生である旨を運営に通知してもらう」のいずれかを行う必要があるでしょう。

この点、どちらが良いと思いますか？あるいは他に案がありますでしょうか？ (To @yoshiokaCB さん)

以下、今後の受付運営について共有しておきたいことを列挙します。すぐに対応すべきことではありませんので、頭の片隅にでも置いていただくと幸いです。
- 現況では影響ありませんが、状況によっては締め切りを延ばすことも可能です。
- 人数の上限設定ですが、会場に入れる人数であれば問題無いです。（上記の25人というのは見込みであり、Maxではありません。こちらで仮に40人としていますが調整が必要です。）

**Comment by sho-h** [comment]
@inoh さん、おつかれさまです！マージと反映をしましたー。

**Comment by Takashi-U** [comment]
すみません。僕の勘違いでした。
チケット自体は分けてあるから、学生かどうかは明示されているということですね。失礼しました。

**Comment by yoshiokaCB** [comment]
@inoh さん @sho-h さん @Takashi-U 
色々ありがとうございます。
参加人数予測ですが、前回は本編には3-5人程度で懇親会は0だったと思います。
学生曰く「懇親会は高くて行けなかった」とのことです。ですので、今回も来ても4-5人程度と思っています。
ただ、学生の場合何かの拍子に大人数申し込まれる可能性も考えときたいです。
面倒ですが、エントリーを分けませんか？分けておいた方が後々の手間がかからないように思います。

**Comment by inoh** [comment]
@yoshiokaCB さん @Takashi-U さん
懇親会のエントリを一般と学生でわけました。
エントリの人数制限を学生は4人、一般は26人としています。
このあたりはエントリの状況で変わってくると思うのでまた指示いただけたら修正します。
@sho-h さん
反映お願いします！
https://github.com/matsuerb/matsuerb-nanoc/pull/207

**Comment by inoh** [comment]
ちなみに学生のエントリはこちらになります。
http://matsue-rb.doorkeeper.jp/events/16899

**Comment by sho-h** [comment]
@inoh さん、おつかれさまです！マージと反映をしましたー。

**Comment by yoshiokaCB** [comment]
@inoh さん @sho-h さん
グッジョブ！
ありがとうございます！
今日はちょっとばたついてて時間が作れなさそうなので、明日あたりに皆さんに告知したいと思います！

**Comment by yoshiokaCB** [comment]
エントリー開始したのでクローズします。
