### ISSUE TITLE
講演開催場所はテルサ中会議室ですか？

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk06#17]
今更ながら私勘違いしていましたが講演の開催場所はオープンソースラボではなくてテルサ中会議室ですか？
ホームページを間違えて記載しておりました。。。

**Comment by sho-h** [comment]
同じ認識でした > OSSラボ

**Comment by inoh** [comment]
ホームページとDoorkeeperに載せる上で少し会場について整理させてください。

**会場について**
- 講演
  - オープンソースラボ
- 懇親会
  - テルサ中会議室
  - カプリチョーザからのケータリング

上記でよろしかったでしょうか？

**Comment by yoshiokaCB** [comment]
@inoh さん

> - 講演
>   - オープンソースラボ
> - 懇親会
>   - テルサ中会議室
>   - カプリチョーザからのケータリング

それでOKです。

**Comment by inoh** [comment]
了解です！
ありがとうございます！
