### ISSUE TITLE
10/25の打ち合わせ時間について

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk06#18]
@yoshiokaCB 
次回の打ち合わせですが何時ぐらいになりそうでしょうか？
別件があってフルに参加が難しそうなので時間をわかれば少し抜けて参加予定です。
もし時間が合わない場合は最悪欠席とさせてもらうかもしれないです。

**Comment by yoshiokaCB** [comment]
全体での打合せって感じはなく、個別に必要事項を相談する感じなので、 @inoh さんには「公開よろしく」って感じの会話で終わると思いますがw
ですので、難しかったらメッセージで募集の開始をお願いをするので大丈夫ですよ。
まぁ、自分は @inoh さんの顔見たいので、ご都合つくようでしたらいらしください！

**Comment by inoh** [comment]
了解しました！
いつもみたいに午後過ぎくらいに少し顔見せに行きます

**Comment by inoh** [comment]
午後行こうと思っていましたがいろいろと立て込んでいて行けそうにないのでまた結果だけ教えてください！

**Comment by yoshiokaCB** [comment]
残念っす！
また公開時期についてはお知らせします！！
