### ISSUE TITLE
役割分担について

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#2]
スタッフの皆さんの役割分担を決めたいと思います。
みなさんのご希望を教えてください。
尚、大まかな役割は以下のページからご確認ください。
https://github.com/matsuerb/matrk06/wiki/%E5%BD%B9%E5%89%B2

また、上記にない役割でもこんな役割も必要じゃない？ってご指摘も歓迎します！

**Comment by amidaku** [comment]
会場係についてですが、前回は役割が曖昧と言うか人により認識が違うような感じがしました。
設備や部屋の手配、必要な機器、レイアウトなど役割を定めておいた方が良いと感じました。
あと、それをひっくるめて会場係とするのか、役割を分離するべきかなど。

さらに、受付やUstの人などは当日は会場準備は余裕が無く対応出来ないので、こういった係りの方は、会場係は兼務出来ないとかんじます。

今日から数日スマホで入力なので文や文字がおかしかったらゴメンね。

**Comment by amidaku** [comment]
あと、当日のマイクやプロジェクター関係で講演者のサポート係がいりますね。
それと、ライブコーディング大喜利するのであれば、それに使用するシステムの担当者も要るような気がします。

**Comment by sho-h** [comment]
Togetter まとめの作成を[前回](http://togetter.com/li/642795)はあみだくさんがやってくださったのですが(http://matsue.rubyist.net/schedule/ にリンク貼りました。ありがとうございました)、今回は誰か担当の人がいるといいかもしれません。

**Comment by yoshiokaCB** [comment]
@amidaku さん、ご指摘ありがとうございます。助かります。
とりあえず、大きく会場係として、後で細かく役割を分けたり、当日までに係の中で相談していこうかなと考えてました。もちろん細かく洗い出してみて、役割を別にして切り分けしたほうが良ければ、そうしようと思います。
あと、ライブコーディング大喜利をする場合、まだ、やり方も曖昧なので、現時点ではどのような環境でするかもわからないので、概要が決まってからどうするか考えようと思ってます。
（多分 @amidaku さんにお願いするかもしれませんが。。。）
会場と受付や撮影関係など、当日忙しい方の兼務なしで、完全に別にしたほうが良さそうですね。了解です！
もう少し詳細を考えて、明日は話してみますね。

**Comment by yoshiokaCB** [comment]
役割についてはwikiをご確認ください。
https://github.com/matsuerb/matrk06/wiki/%E5%BD%B9%E5%89%B2
自分の役割が違うって人は申告をお願いします。
名前の無い方については当日の会場準備等お願いしたいと思っています。
また、細々とした仕事が出てきますので、その都度、声かけさせてください。
