### ISSUE TITLE
Matsue.rbのTシャツ作成

### ISSUE THREAD

**Issue by AyakoMakihara** [matsuerb/matrk06#20]
松江Ruby会議05で作成したTシャツを追加作成します。
- [x] 注文する人を取りまとめて枚数を確定（11/15頃）(15)
- [x] サイズの取りまとめ（11/15頃）
- [x] データの受け渡し
- [x] tmixに注文（到着2週間前　11/29頃）
- [x] 受取（12/13には欲しい）

:rabbit2: サイズ別注文リスト 

| 　サイズ　 | 枚数　 |
| --- | --- |
| 160 | 2 |
| S　 | 1 |
| M　 | 5 |
| L　 | 6 |
| XL　 | 0 |
| XXL | 1 |
| 合計 | 15 |

**Comment by yoshiokaCB** [comment]
今のところ把握しているのは。。。

| 名前 | サイズ |
| --- | --- |
| 野坂さん | XXL |
| 槙原さん | 160 |
| 原田さん | L |
| 小埼さん | M |

**Comment by sho-h** [comment]
@AyakoMakihara さん、よろしくお願いします。m(_ _)m

先日本件用にTシャツデータをいただきました。後ほどお送りします。この件を最初のコメントに追記しました。

**Comment by AyakoMakihara** [comment]
@yoshiokaCB @sho-h :ok_woman:

**Comment by sho-h** [comment]
@yoshiokaCB さん、ゲストさんお二人のサイズってMでしたっけ？

**Comment by yoshiokaCB** [comment]
えーと、倉貫さんともう一人は岡山から来られる予定ですがサイズは分からないですね。
本人に聞くのもサプライズ感がなくなるのでプレゼント（あまり）とゲストにお渡しするのを合わせてM, L 各2着ずつ頼むのはどうでしょうか？

**Comment by sho-h** [comment]
なるほどです！

**Comment by AyakoMakihara** [comment]
@sho-h データ受け取りました :ok: 
@yoshiokaCB 注文リストML +2にしました :ok_hand:

**Comment by yoshiokaCB** [comment]
@AyakoMakihara さん
あと、５着でしたよね？
L 2
M 1
S 1
160 1
でどうでしょうか？
大は小をかねるということで。

**Comment by AyakoMakihara** [comment]
@yoshiokaCB :ok_hand: これで、注文を行います♪

**Comment by AyakoMakihara** [comment]
注文完了！ :ok:

**Comment by inoh** [comment]
:+1:

**Comment by AyakoMakihara** [comment]
本日11/27に　Ｔシャツが到着予定です :octocat:

**Comment by sho-h** [comment]
:+1:

**Comment by AyakoMakihara** [comment]
当日、配付します :rabbit2:
