### ISSUE TITLE
ライブコーディング大喜利　問題

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#22]
ライブコーディング大喜利の問題を作成してみました。

http://qiita.com/yoshiokaCB/private/1be71c5cd588a1166321

もっとこうした方が良いとか、こんな問題を出した方が良いとかありましたらご意見をお願いいたいs増す！

@sada さん
問題作成よろしくお願いします！

**Comment by sho-h** [comment]
Array#shuffle系では#sampleも禁止した方がいいかもですね。:)

```
[1,2,3,4,5].sample(5) # => [2, 3, 4, 5, 1]
```

**Comment by yoshiokaCB** [comment]
あ、ですよね。。。
数日前にある人にそんなメソッドがあること教えてもらいました(^^;)
さっそく修正しました！

**Comment by sada** [comment]
@yoshiokaCB さん
こちらの作業を出来ていなくて申し訳ありません。
問題の作成の締切りはいつでしょうか？

**Comment by yoshiokaCB** [comment]
@sada さん
特に決めてないですが、まぁ、ボチボチと。。。
お困りでしたら野坂さんにご相談してみては？
きっと良いアイディアをいただけると思います！

**Comment by yoshiokaCB** [comment]
@sada さん
ごめんなさい。答えになってないですね。
来週中とかでどうですかね？

**Comment by sada** [comment]
@yoshiokaCB さん
了解しました。
来週中までに幾つか問題を作成してみます。

問題は作成次第、Qiitaの問題の記事へコメントで共有すれば良いでしょうか。

**Comment by yoshiokaCB** [comment]
@sada さん
あっ、Qiitaの問題はあくまで出題用にしようと思うので、こちらに一度上げてもらって良いでしょうか？こちらの方が他の方の意見も拾いやすいかと思いますし。
（そのまま掲載だとは思いますが。）
最終的には、私の方でQiitaへはアップさせていただきます！

**Comment by sada** [comment]
@yoshiokaCB さん
こちらに問題を投稿する旨、了解しました。

**Comment by sada** [comment]
以下の問題を考えましたが、大喜利要素がないので悩んでいます。

問４ 漢数字

数値を漢数字に変換するプログラムを作成してください。
数値は、以下のような0から1_000_000_000_000_000のいずれかです。

<pre>
num = rand(1_000_000_000_000_000)
# -- ここにコードを記述してください。 --
</pre>

以下は、作成するプログラムの内容です。
- 「0」は「零」を返す。
- 「23」は「二十三」です。
- 「100」は「百」です。
- 「5000」は「五千」です。

プログラムが返す漢数字は、標準出力に出力してください。

**Comment by sada** [comment]
以下のような問題の方が色々な方法が出てきそうな気もします。

問５ Hello World

以下のプログラムが書かれたhello.rbファイルがあります。

<pre>
puts("Hello World!")
</pre>

hello.rbファイルは、以下のコマンドで実行時に標準出力へ「Hello World!」と出力します。

<pre>
$ ruby hello.rb
</pre>

プログラムまたはコマンドに変更を加え、実行時に標準出力へ何も出力されないようにください。

**Comment by sada** [comment]
問６ 確率

0回から13回までのいずれかの回数だけトランプのカードを引けます。
引いたカードが、すべてスペードの絵柄である場合の確率を返すプログラムを作成してください。

以下は、トランプの内容です。
- トランプの枚数は、52枚です。
- トランプの絵柄は、「スペード、クローバー、ハート、ダイヤ」の4つです。
- 絵柄ごとにカードは、13枚あります。
- カードの種類は、「A 2 3 4 5 6 7 8 9 10 J Q K」の13種類です。

**Comment by yoshiokaCB** [comment]
@sada さん
問題ありがとうございます！
また後ほどじっくり見させていただきます！！

**Comment by yoshiokaCB** [comment]
問6を採用することにしました！
@sada さん、ありがとうございました！！
