### ISSUE TITLE
ウェブサイトの出演者とタイトルの更新

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#23]
@inoh さん
ゲストが決定しましたので、更新をお願いします。

講演タイトル：「納品のない受託開発」と、エンジニアの働きかたのこれから
講演者：株式会社ソニックガーデン　倉貫義人氏

**Comment by inoh** [comment]
修正してプルリクしました。
https://github.com/matsuerb/matsuerb-nanoc/pulls

**Comment by sho-h** [comment]
どもでした。昨日反映しましたー。

**Comment by yoshiokaCB** [comment]
ありがとうございます！
