### ISSUE TITLE
3つのdoorkeeperのリンクの_blankあるなし

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk06#24]
公式サイトのdoorkeeperのリンク、参加受付だけtarget="_blank"が付いてるんですね。去年はどうかなと思ったらないようでした。今回付けたという事は残り2つも付けようと思ってた感じでしょうか？

**Comment by sho-h** [comment]
matsuerb/matsuerb-nanoc@d4d70b9 の修正っぽいですね。

**Comment by inoh** [comment]
ご指摘ありがとうございます。
失礼いたしました。
私の修正漏れでしたのでtarget="_blank"を一律つける形で修正しました。
https://github.com/matsuerb/matsuerb-nanoc/pull/212
よろしくお願いします。

**Comment by sho-h** [comment]
ありがとうございます。反映しましたー。

**Comment by inoh** [comment]
ありがとうございます！
