### ISSUE TITLE
まつもとさんへのお礼を考える。

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#26]
大問題です。
まつもとさんへのお礼を考えていませんでした。
Tシャツは昨年お渡ししてますので、今年もお渡しする訳にはいきません！
皆さんどうか良いお知恵を！！

**Comment by yoshiokaCB** [comment]
今年は物をお渡しできないので、Rubyに対して貢献したことをお伝えしたいと思います。
- smalrubyを開発してRubyの普及とプログラミングの普及に努めています。（高尾さん）
- スプラウト.rbというコミュニティーを立ち上げてRailsの普及につとめています。（松岡さん）

それで、来年はもっと貢献した人が増えるようにがんばりますとお伝えしたいと思います！

**Comment by KatoAtsue** [comment]
記念品のようなものを作っていますが、まだ現物が届かないので自信がないです。
また届いたらご連絡します。

**Comment by yoshiokaCB** [comment]
@KatoAtsue さん
ありがとうございます！
楽しみにしております！！

**Comment by KatoAtsue** [comment]
![totebag](https://cloud.githubusercontent.com/assets/5475425/5178690/837b7ffe-74b4-11e4-8e4d-73081c7203dc.jpg)
今日届きましたので、もしよかったら差し上げてください。
日系研修員の方にもよかったら差し上げてください。
Mサイズ2枚とSサイズ5枚ありますが、できれば自分用に1、2枚残していただければと思います。
正直いらなかったら遠慮なく却下してください。

**Comment by yoshiokaCB** [comment]
@KatoAtsue さん
いいですね！
個人的にはいただけるとすごく嬉しいです！！（ご迷惑でなければ。）
一応他の人の意見も聞いてみますね。
あっ、自分用はちゃんととっておいてくださいね。

**Comment by KatoAtsue** [comment]
どうもありがとうございます。

**Comment by sho-h** [comment]
:+1:

**Comment by KatoAtsue** [comment]
特に問題なければ、Mサイズ1枚、Sサイズ4枚を当日持参します。
講演または参加される方にお渡しいただけると嬉しいです。
余ったら持ち帰るので会議の進行上負担にならないようにしてください。

**Comment by yoshiokaCB** [comment]
@KatoAtsue さん
ぜひぜひ、お願いします！

一枚はまつもとさんへお渡しして、残りを懇親会のじゃんけん大会に使用したいと思います！

**Comment by KatoAtsue** [comment]
吉岡さん、どうもありがとうございます。よろしくお願いします。
