### ISSUE TITLE
当日撮影した写真をどこかに保存する。

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#27]
当日写真を撮影しますが、その写真はどこに保管しましょうか？
候補としてはFrickerとか、Instagramとか。。。

ご意見お願いします！

**Comment by KatoAtsue** [comment]
参考のためにFlickrにアカウントを作って松江Ruby会議05の写真をアップロードしてみました。
https://www.flickr.com/photos/kato-atsue/sets/72157649030898759/

**Comment by inoh** [comment]
Flickr
:+1:

**Comment by yoshiokaCB** [comment]
めっちゃいいですね！
ありがとうございます！！
filckerで進める方向がいいですかね。
Matsue.rbでアカウントを作るかどうか確認してみますね。

**Comment by KatoAtsue** [comment]
ありがとうございます。
よろしくお願いします。

**Comment by yoshiokaCB** [comment]
@takaokouji さんがMatsue.rb用のアカウントを作成します。
作成後、 @KatoAtsue さんへアカウント情報を教えてあげてください。
お二人ともよろしくお願いします。

**Comment by inoh** [comment]
@yoshiokaCB さん @takaokouji さん
Flickrアカウントどうしましょう？
もしあれば事前に確認しようと思いましたが急がないようであればRuby会議後日に改めてでよいかと思います。

**Comment by yoshiokaCB** [comment]
えーと、今のところ高尾さんと相談中でして、二人の希望としてはmatsue.rbのサイトのどこかに画像ライブラリーのページを作りたいねと協議中。
なので、とりあえずどこかにひとまとめにしてもらえると助かります。
（web上でもローカルでもOK）

**Comment by inoh** [comment]
了解しました。
また共有しやすい形でまとめて画像提供できたらと思うのでまた写真班で調整してつなぎます

**Comment by takaokouji** [comment]
> @takaokouji さんがMatsue.rb用のアカウントを作成します。

ごめんなさい :bow: これは難しくなりました。
アカウントの作成には、携帯の電話番号が必要なのですよね。Matsue.rb用というのが難しくて...

ということで、

> 二人の希望としてはmatsue.rbのサイトのどこかに画像ライブラリーのページを作りたいねと協議中。

で進めていて、なおかつ、1セッションに1、2枚程度の写真を想定しています。
ウェブ担当の方に、写真担当の方が、選考した写真をアップロードしていただく必要がありそうです。

**Comment by takaokouji** [comment]
写真付きで開催レポートを公式サイトでも公開できるといいな〜と、勝手に思ったり...
ちょっと当日にウェブ担当のみなさまと相談ですね :smiley_cat:

**Comment by sho-h** [comment]
電話番号って「パスワード忘れたらここにメッセージ送るね」って書いてあるんですけど、あまり問題があるように見えませんでした。重複ができないとかですか？

**Comment by takaokouji** [comment]
> 重複ができないとかですか？

はい、そういう想定です。が、違うのかな... :sweat_smile:

**Comment by Takashi-U** [comment]
一つの案ですが、Flickrで例えば松江Ruby会議06Groupを作成して、写真を撮影した皆さんがそのGroupに写真を供与するというのは考えられます。

メリットとしては、（メンバーも概ね同じですし、脱落するというのは基本的に無いでしょうから）次回以降も同じ仕組みで行えること、通常の活動についても活用できること、等があるでしょうか。

デメリットとしては、写真を供与する人がそれぞれにFlickrのアカウントを取得する必要があること等でしょうか。。

案です。はい。

**Comment by takaokouji** [comment]
ふむふむ。
すみませんが、写真担当の方で良さそうな方法を検討いただけるとありがたいです。

2014年12月18日木曜日、Takashi Uchibenotifications@github.comさんは書きました:

> 一つの案ですが、Flickrで例えば松江Ruby会議06Groupを作成して、写真を撮影した皆さんがそのGroupに写真を供与するというのは考えられます。
> 
> メリットとしては、（メンバーも概ね同じですし、脱落するというのは基本的に無いでしょうから）次回以降も同じ仕組みで行えること、通常の活動についても活用できること、等があるでしょうか。
> 
> デメリットとしては、写真を供与する人がそれぞれにFlickrのアカウントを取得する必要があること等でしょうか。。
> 
> 案です。はい。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matsuerb/matrk06/issues/27#issuecomment-67458049.

## 

Kouji Takao kouji.takao@gmail.com

**Comment by sho-h** [comment]
ふーむ。とりあえずどうするかは別として質問した理由を書いてなかったので書いてみます。

写真係の皆さんがよければ実は問題はありませんが、特に誰からも意見が出ない場合は僕は各セッションに1、2枚というのは反対したいなぁと考えています。というのも数名の方に撮っていただくのですが、その数だとどなたかの写真が全てが採用されない可能性がある事を危惧しています。公開前提で折角撮っていただく訳ですのでできる限り公開したいです。

Yahooアカウントのヘルプを見る限りでは重複できないかはよくわかりませんね。[Rails Girlsでも写真をまとめて](https://www.flickr.com/photos/109849144@N02/)いるので、本当にそうなのかなとは思いました。これがGroup？

> 写真付きで開催レポートを公式サイトでも公開

今気づいたのですが、(本筋じゃないけど)これはRubyist Magazineに載った後でという感じです？前ならレポートの意味によっては割と強く反対したいと思っています。「開催しました」くらいの意味合いであれば特に異論はないのですが。(@sho-h もうちょっと動けよという事でもあります)

**Comment by takaokouji** [comment]
@sho-h ちょっと補足ですが、1, 2枚というのは、
- Flickr は電話番号が必要なのでMatsue.rb用のアカウント作成は難しそう(実際にそうなのかは試していません...)
- ということで、画像は公式サイト(GitHub pages)に配置する
- 容量も限られているし、checkoutしたときに容量が大きいのもあれなので、各セッションで 1, 2枚かな〜

といったことから、吉岡さんと相談していました。
もし他の手段でかつ、私ではない方が作業されるのでしたら、どのような方法でもOKです :smiley: 

> 今気づいたのですが、(本筋じゃないけど)これはRubyist Magazineに載った後でという感じです？前ならレポートの意味によっては割と強く反対したいと思っています。

特に時期は考えていませんでした。みなさんの思うようにしたいですね。開催レポートは Rubyist Magazine へのリンクでも良さそうですね。

**Comment by takaokouji** [comment]
いまこのissueを読み直してみると、私は共有アカウントの作成だけを依頼されていたので、「共有アカウントの作成は難しいです、ごめんなさい :bow: 」とだけ相談すればよかったのですね。公開方法まで考えてほしいとは相談されてなかったですね。しまった orz

**Comment by sho-h** [comment]
> ちょっと補足ですが、...

そうですね。GitHub Pagesは結局GitHubにコミットするので1ファイル50MB未満だったり、全体で容量が...とかいう理由だとは思っていました。でも試してすらないのに提案する内容としてはやっぱり重いと感じます。といってもやっぱり写真係の方々の都合がよければそれで問題ないのですが...

> 特に時期は考えていませんでした。みなさんの思うようにしたいですね。開催レポートは Rubyist Magazine へのリンクでも良さそうですね。

つまり、「レポート」の意味はRubyist Magazineに載るような内容のものを指すという事ですね。ではリンクを希望します。

**Comment by amidaku** [comment]
ちょっと部外者が整理かけますが、要件的に
- いっぱい保存できる
- 複数の人がUPする
- UPした物が閲覧できる
- 必要なら（それなりの解像度で）ダウンロードできる

と言うことなのだと感じました。
全ての要件を満たすとなると、アップロード制限はありますが、撮られた方全員がアカウントを作成してFlickr等へあげるしかないと思いました。

あとは何かアプリをクラウドサーバにインストールして...
ファイルの保管だけとかであればいろいろ考えられると思いますが、閲覧したりその他を考えると皆さんがアカウントを作られるのが普通な感じがします。

Flickrもそうですが、instagramやFacebookもアップロードされたファイルの品質は落として公開されるので、そのあたりはご留意ください。

**Comment by takaokouji** [comment]
> 提案する内容としてはやっぱり重いと感じます

たしかに、たしかに...
提案はなかったことに... ならないですかね :sweat_smile:

**Comment by Takashi-U** [comment]
https://www.flickr.com/groups/matsue/

Groupの例です。

**Comment by inoh** [comment]
皆様いろいろとアドバイスありがとうございます。
私が考えていた途中経過です。
松江ruby会議用のFlickrアカウントですが私も実際作成しようと思いましたが同一の電話番号で複数アカウントは作れましたが結局同一のFlickrの領域になってました。
Flickrの共有も考えましたが私が経験がなく少しハードルが高いように思えたので下記の２点の案に絞っていました。
1. GoogleDriveで写真を共有
2. Facebookで写真を共有

1については写真が劣化しないというメリットがありますが共有の設定がいるのでメンバ追加がめんどう。
2についてはすでにFacebookのグループがあるのでそこのアルバムにそのままあげれば準備が不要。
ということでとりあえず写真を共有するという点でFacebookにあげることを考えていました。
たとえFacebookにあげたとしてホームページにあげるレベルであれば問題ないように思います。
それに原本はあるはずなので最悪もらい直せば大丈夫だと思います。
あと参加者の写真撮影有無の問題もあるのでできれば公開されてない領域がよいというのもポイントに考えています。

**Comment by amidaku** [comment]
:smile:

**Comment by ToruKurahashi** [comment]
横からすみません。サーバ立てるの得意な方がhttps://github.com/afternoonrobot/photographer-ioとかサクッと構築してみるとか。

**Comment by yoshiokaCB** [comment]
Facebookに掲載もいいですね！

原本ですが、出来ればそのときに集めておきたいです。（当日という意味ではなくても）
なので、写真班に撮影した写真を集める方法だけ当日考えてもらいましょう。
もしくは、どこかにアップではなくその日にリーダー使って画像をもらうでも良いです。
一応言い出しっぺなので自分リーダー準備しておきます。

それの共有をどうするかは、また相談しましょう。まぁ、基本FBかFlickrが良いかなとも思っています。個人個人でFlickrを使用するのがハードルが高いならまとめた者を自分でアップロードしますので。

**Comment by yoshiokaCB** [comment]
あっ、ごめんなさい。まだ相談しましょうじゃないや。

@KatoAtsue さん　 @inoh さん　@AyakoMakihara さん　 @tomo-k さん
希望として原本は何らかの方法で当日か次回の定例会くらいまでで集めときたいです。
必要な時にもらい直すのはやりとりが大変かなと思ってのことです。
あとは写真班のみなさんがどの方法が共有しやすいか相談が必要かもしれないですね。
日にちないんで、当日、少し話し合ってもらうとかできますか？
多分あって話せば5分くらいで終わると思いますんで。
FBでもFlickrでもGoogleDriveでもなんでもいいですよ。

@sho-h さん
ウェブサイトでの掲載は橋本さんの意見もごもっともだと思います。
なので、写真の選考方法も含め、その件は1月の定例会のときにでも相談させてください。
（そんなに急ぐことでもないと思っているので。）
ちなみにるりまに掲載後ならレポート付きでも良いですか？同じような内容のページ作るのはよくないんですかね？
個人的にはMatsue.rbのコンテンツが少しずつでも増えると楽しいので、何らかの形でRuby会議06の様子を掲載したいですね。

@ToruKurahashi さん
サーバの話も面白そうですね。
ずっと使うなら構築してみるのも良いかもしれませんね。
もちろん倉橋さんが立ててくれるんですよねwww

**Comment by sho-h** [comment]
@yoshiokaCB さん、掲載については僕的には撮ってくださった皆さんの合意が得れていれば特にですが、Flickrがどうしてもダメという事があればGitHub Pagesにコミットしてしまう案を一度検討してもらったらいいのかなとは考えています。重い言うても僕が待てばいいだけですので。サイズについてはGB単位になってから気にする案です。
レポートについては別にダメって言われた事はありませんが、Rubyの会の支援を受けてる&&支援に対してレポートを書いていると思っているので同じような内容であればRubyistMagazineへの掲載後を希望する立場を取りたいと考えています。読者のためには初出はRubyistMagazineにすべきかなと勝手に考えてるだけなのですが。なので「開催しました」程度であれば特にという考えです。

@ToruKurahashi さん、サーバを立ててくださるとは...櫻井翔ばりの@ToruKurahashi さんのダブルパーカー写真の掲載が楽しみですね。

**Comment by inoh** [comment]
@yoshiokaCB さんが言われるとおり、当日に写真の受け渡しですがシンプルに考えて原本がいる方に直接PCへコピーしてもよいかと思いました。
なんならCD（DVD?）も持参して欲しい人には焼いてくばっちゃうのもありかもと思いました。

@sho-h さん
FlickrやGitHubを採用しなかった理由ですが撮った側が公の場と気にせず写真を選ばずぽんぽんあげれればという気持ちからでした。
Flickrならいろいろと設定があるのでいじればできそうですがそのあたりも含めてまた当日相談させてください！
@AyakoMakihara さんがrailsgirlsでアカウントをとっていたのでもしかしたら電話番号同じでも別にとれる？と期待もしてます。

@ToruKurahashi さんがサーバを立ててくださるそうなのでとりあえず気にしなくてよさそうな雰囲気...です？

**Comment by sho-h** [comment]
@inoh さん
あ、ごめんなさい。選別は今のままで異論ないです。その後でFlickr でも Facebookのグループでそのまま公開する？でもCDでもいいと思いますが、僕が追加で提案させてもらったのはどれも選択肢として不当ならGitHub Pages(公式サイト)に枚数を気にせずあげたらいいんじゃないかというものです。僕が嫌なのは人数の割に厳選された十数枚だけ公開するという事を気軽に選択するという事だけです。

**Comment by sho-h** [comment]
あとそういえばRails Girlsのドキュメントで賢いなと思ったやり方を思い出したのですが、画像はdropboxなどに挙げておいてGitHub Pagesからはそれを直接表示するというものでした。ドキュメントだと画像の差し替えが楽というメリットがありますが、今回の場合はサイズを気にしなくていいというくらいかもですね。

**Comment by yoshiokaCB** [comment]
@sho-h さん
了解っす。お気持ちわかりました。支援 = 執筆料 と考えるとしっくりきますね（あってる？）
自分もせっかく皆さんが撮影してくれた写真なので、すべてどこかで見れるようにしたいと考えています。それがFBなのかFrickrなのかGoogleDriveなのかはまた写真班の方へ協議してもらいましょう。

githubにそのままのサイズで全部載せるのはちょっと気になりますね。というのもgit clone とかしたときにしたときに時間がかかりそうで。。。新しくメンバーのところを修正してもらう人のにハードルが上がるかなと。
なので、開催されました的なページはまたご相談させてください。文字のやり取りだと大変なんで。

あっ、「るりま」って書いてたwww

@inoh さん
CD/DVDのライターもってないっすw
cdやdvdなら何枚か持っていきますよ。

**Comment by amidaku** [comment]
当日中継関係でMBP17持って行くので、中継時間じゃなかったらＤＶＤ焼けますよ。ただ懇親会は出ないので時間的にアレかもですが。

**Comment by sho-h** [comment]
git cloneについては確かにGitHub Pages を選択する場合はmatsuerb-nanocの方は何かしら工夫が必要そうですね。matsuerb.github.ioだけにすれば影響は最小です。matsuerb-nanocで必要な人だけがコマンドで写真取ってくるとかを考えていました。

**Comment by yoshiokaCB** [comment]
@amidaku さん
うーん時間ないかもしれないですね。
そもそも焼くかどうかもまだ確定ではないので、大丈夫ですよ。

@sho-h さん
了解っす！何か解決策あるならそれも検討材料にしましょう！

**Comment by yoshiokaCB** [comment]
@inoh さん
写真受け取りました！
ありがとうございます。
あとは上記参考にどこかで公開できるように作業を進めます。

ちなみにいただいた画像のトータルのサイズが4Gを超えており、このままGithubとかで共有するのは色々と大変だなぁと思っています。
FBはあくまで写真共有のサービスではないので、FlickrかInstagramあたりで上手くできないか調べてみます。

あっ、 @ToruKurahashi さんがサーバを構築してくれることに期待しましょう！

**Comment by sho-h** [comment]
FlickrやInstgramでも縮小されるみたいな話が挙がってたのでGitHubに挙げるにしても(残念ながら手作業で)リサイズしたものを想像していました。選別後リサイズ後ですので多くても100MB程度とかを想像してますです。(4GBでも自分は別に気にはしませんよ)
ただ、GitHubは最後の手段みたいなものだと思ってるので、Flickrとか使いやすそうなもの優先のまま検討いただければと思います。

**Comment by yoshiokaCB** [comment]
このアドレス見れますかね？
https://www.flickr.com/groups/2847723@N21/pool/

確認できれば、matsue.rbのお知らせにpushしまーす。

**Comment by ToruKurahashi** [comment]
見えますた。

**Comment by yoshiokaCB** [comment]
あざっす。やっぱ自分の設定でよかったんだ。安心しました。
今週末終われるように作業続けます。

**Comment by yoshiokaCB** [comment]
写真をFlickrにアップリしてMatsue.rbのサイトにリンクを貼ったのでクローズします。
http://matsue.rubyist.net/news/2015/02/28/matsue-rubykaigi06/
