### ISSUE TITLE
問い合わせメール不通

### ISSUE THREAD

**Issue by shugo** [matsuerb/matrk06#28]
> "松江Ruby会議06に関するお問い合わせは、matsuerubykaigi06@googlegroups.comまで" matsue-rb.doorkeeper.jp/events/16078 とあったが "Delivery Status Notification (Failure)" と言われてしまった
> https://twitter.com/_ko1/status/537478816528990208

という話を見かけたのですが、どなたか対応できる方はいらっしゃいますか？

**Comment by yoshiokaCB** [comment]
@shugo さん
ご指摘ありがとうございます！

@sho-h さん、@takaokouji さん、@inoh さん
googleのメーリングリストってメンバー以外でも送れたんですっけ？
うっかりしてました。
メンバー以外から送れない場合、今更ですが代わりのメールを準備したいです！

**Comment by nishidayuya** [comment]
https://support.google.com/a/answer/170452?hl=ja によると，

> [公開]: 誰でもメッセージを送信できる汎用的なグループを作成するには、このオプションを選択します。たとえば、このオプションを使用して、営業やサポートなど、ドメイン外のユーザーからの窓口となる部署やチームで使用できるグループを作成できます。
> 
> グループにメッセージを送信できるユーザー: ドメイン内外のすべてのユーザー

ということですのでできそうです．権限のある方，確認お願いします．

**Comment by yoshiokaCB** [comment]
@nishidayuya さん
ありがとうございます。
確か設定したのって @inoh さんでしたっけ？
確認をお願いします！

**Comment by inoh** [comment]
設定を確認しましたが **投稿権限** が **グループ内** に限られていました。
投稿権限を **一般** に変更してグループ外のメールから確認したところ送信ができることを確認しました。
今まで問い合わせがあってもとれてなかったってことですね。。。失礼いたしました。

**Comment by yoshiokaCB** [comment]
@inoh さん
ありがとうございます！助かりました！！
ちゃんと確認しないとダメですね(^^;)　色々と油断してました。
こちらこそ失礼しました。

@shugo さん
ツイートされた方とは直接やり取りをしてましたので、特に連絡の必要はないかと思いますが、一応問い合わせ用のメールが使えるようになったということをお伝えいただいてもよろしいでしょうか？
色々とありがとうございました。
