### ISSUE TITLE
サイトにバナー広告を掲載する

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#29]
@inoh さん

すみませんが、スポンサーに2社追加をお願いします！
- Nacl ネットワーク応用通信研究所
- ファーエンドテクノロジー株式会社

画像は後ほどお送りします。

**Comment by inoh** [comment]
了解でーす

**Comment by inoh** [comment]
修正してプルリク送っておきました！
https://github.com/matsuerb/matsuerb-nanoc/pull/222

**Comment by yoshiokaCB** [comment]
確認しました。ありがとうございます！
