### ISSUE TITLE
懇親会会場の予約

### ISSUE THREAD

**Issue by Takashi-U** [matsuerb/matrk06#3]
@kazuki-harada さん、と@Takashi-Uでやります。

**Comment by kazuki-harada** [comment]
がんばります^^

**Comment by Takashi-U** [comment]
少し関係者と話をしました。
方針としましては、テルサでケータリングという事で準備したいと思います。

**Comment by Takashi-U** [comment]
12/20土曜日、カプリチョーザのケータリング、松江テルサ中会議室の予約を完了しました。
必要な備品を数日以内に決めて再度事務局へお伝えし、会場料金を確定せねばなりません。

@yoshiokaCB さん、この点ご指示いただけませんでしょうか？
@kazuki-harada さん、今のところ備品のお金と会場のお金は、併せて（明細はどうなっているかわかりませんが）請求をあげて貰う事で話をしています。もしも、今後追加で備品が必要になった場合、請求が分かれたり、支払が別々になっても問題は無いでしょうか？

以下、現況も併せて挙げておきます。
- 18時〜22時でおさえています。
- ケータリングは1名4,000円です。
- 仮に30名で予約をしています。

**Comment by yoshiokaCB** [comment]
備品はプロジェクター、スクリーン、マイクくらいかな。
あと、wifiが使えると、なお良いって感じ。まぁ、LTするだけだしwifiはなくても何とかなるかも。
他に何かいるかな？
ホワイトボードがあると何かに使えるかな？
（wifiのidとpass書いたりとか）

**Comment by Takashi-U** [comment]
ラボの備品というのは使ったらダメなんですかね？
よく考えたら、前回の知見があるので、 @ToruKurahashi さんに降臨して頂くと助かります。

**Comment by amidaku** [comment]
WifiとかLAN系は懇親会の後で、また片付けが発生するから面倒かな...とか言って見たりするテスト

**Comment by ToruKurahashi** [comment]
横からすみません。いろいろ分かっていないことが多くて、前知識として質問させて下さい。
・会場費はどこから出ますでしょうか？
・カプリチョーザのケータリングの最低料金は分かりますでしょうか。
といいますのも、たしか前回の懇親会参加者数は２３人だったと思いますが、今回３０人以上集まるのかなと思った次第です。
よろしくお願いします。

**Comment by yoshiokaCB** [comment]
@amidaku さん
おお！そうですね。やめましょう。

**Comment by Takashi-U** [comment]
- 会場費は @kazuki-harada さんの筋から
- ケータリングは4,000円が最低料金

となっております。
予約自体を現在30名で行っている状況です。そこの辺りは留意して進めたいと思ってはいますが、何か問題があれば随時ご指導頂ければと…。

**Comment by amidaku** [comment]
会場費は上限とか考えなくて良いって感じですか？
備品とかできれば借りた方が楽かなと。
あと金集めて会場使うので、会場費用がちょっと高くなると思いましたがその辺はOKですか？ > @kazuki-harada

**Comment by ToruKurahashi** [comment]
@Takashi-U さん了解です。

会場費は「心配無用」ということですね。
ということであれば、借りれる備品はテルサで借りた方がよさそうですね。何が借りれそうか確認してから決めたらいかがでしょうか。足りないもので手間にそれほどならないものはラボから持って来てもいいかもしれません。

カプリですが、カプリのお店貸切の場合、人数ではなく最低料金が設定されています（たしか１５万円から１８万円くらいだったような）。ケータリングの場合は私は知りませんが、３０名を２０名とかに変更しても問題ないか、一度お店に問い合わせをしておいた方がよいかもしれません（もしケータリングの最低料金が分かれば聞いておいて頂けると、これからの参考になります）。

**Comment by Takashi-U** [comment]
@amidaku さん、僕の認識では非営利目的の懇親会で料金は低い方だと思ってました。ただ、会場費予算にはかなり余裕がありますので、その点は備品等も含めて必要なものは十分準備できると思います。もちろん、なるべく安くしようとは思います。

@ToruKurahashi さん、お店貸し切りについては「30人下回るけどどう？」でNGでした。僕「じゃぁケータリングですね」お店「そうですね」というやり取りでしたので、下限があるとしたらえらいこっちゃです。助かります。確認してみます。

**Comment by amidaku** [comment]
@Takashi-U ぁ、ですね。5000円超えなきゃ非営利価格でした。ゴメンナサイ。
では心配なくテルサさんのプロジェクタ等でやりましょう。
中継はしませんが、一応1カメラで録画はするつもりです。

**Comment by Takashi-U** [comment]
@amidaku 念のためテルサに食費4,000円として伝えました。審査して請求起こすので、請求書を見てねという回答でしたが、amidakuさんの基準であれば問題無さそうですね。

**Comment by Takashi-U** [comment]
@ToruKurahashi ケータリングは特に下限を設定していないとの事です。理屈としては、店舗の通常営業を妨げないこと、会場費はお客様持ちであることのようです。
極端な話（例えば、一人からでもケータリングOKなのか）は聞いてませんが、20人ぐらいになったりしても大丈夫かと聞いたときに、問題無いとの事でした。

ちなみに、料理の内容によっては、3日前ぐらいから人数が動かせない（キャンセルが発生する）ようです。カプリチョーザ単独で準備できる料理であれば、極端な話当日でも対応出来る場合があるようです。
というわけで、おかげさまをもちまして、カプリチョーザ単独で準備できる料理で御願いしておきました。

**Comment by amidaku** [comment]
よく考えたら、懇親会参加しないかもしれないので先の録画の話は現時点で無しにしておいてください。

**Comment by ToruKurahashi** [comment]
@Takashi-U さん、ありがとうございます。とても参考になりました。
あと、特別な参加者に懇親会無料とか学生半額とかはお考えでしょうか？

**Comment by Takashi-U** [comment]
@ToruKurahashi さん、その辺りは @yoshiokaCB さんと相談中の案件でございます。何らかの配慮はしたいという方向ですが、どういった形で実現するか、あるいは断念するかはこれからです。

お知恵があれば…

**Comment by ToruKurahashi** [comment]
カプリの飲み放題は１５００円なので、学生さんから２０００円頂いて、５００円分は食事の追加分にまわすというのはどうでしょうか。全体的な食べ物の量は減りますが、カプリは比較的量が多い方だと思いますので、大丈夫だと思います。

**Comment by kazuki-harada** [comment]
中学校Ruby授業の教員研修に出ておりまして、今戻りました。

松江市から執行できる「会場費」の上限は、３３，０００円です。
なお、予算は「会場費」はOKで、「備品代」は０円で査定されています（ケチ）ので、「会場費」の請求しか予算執行できません。

2014年8月8日 13:35 Toru Kurahashi notifications@github.com:

**Comment by Takashi-U** [comment]
な、なんと！

**Comment by kazuki-harada** [comment]
そ、そのようにfacebookでもお、おつたえしていましたよ、よ(**)

2014-08-08 18:54 GMT+09:00 Takashi Uchibe notifications@github.com:

**Comment by Takashi-U** [comment]
会場費の意味を取り違えてました。大変失礼しました。

であれば、とりあえずはこのまま予約し、片付け等の面倒臭さは何とかするという方針でいかせてください。

**Comment by Takashi-U** [comment]
中会議室の利用料金のみで請求を御願いしました。
備品は別途テルサ事務局に御願いする事になります。

【備品について】
@amidaku さん
@yoshiokaCB さん
先日少しお話をしたと思いますが念のため
- 音響ワゴン（1,080円）
- ワイヤレスマイク2本（1本あたり648円）

を御願いするということで良いでしょうか？
- 映像ワゴン（2,700円）

は無しで良いでしょうか？

また、別途電源使用量がかかるかと思いますので、念のため付記致します。
上記備品については、懇親会費に会場費を上乗せする形（500円程度）であることも、確認の意味を込めてこちらに付記しておきます。

**Comment by amidaku** [comment]
音響関係はそれで良いです。
もしマイクスタンドが必要ならそれを追加となります。
（床置きスタンドと卓上スタンドがあります。）
また、LTで両手を解放する必要があれば、ワイヤレスマイクをひとつハンドマイクからタイピン型にしてもらう方が良いと思います。

映像ワゴンは可搬型のプロジェクタだと思います。
天井にプロジェクタがある部屋なら不要です。

**Comment by Takashi-U** [comment]
プロジェクターを使いたいという旨を伝えたら、映像ワゴンが必要ですと言われました。（中会議室の利用前提での話です。）

プロジェクター持ち込み前提であれば、使えればラッキー程度に考えれば良いでしょうが、持ち込みを全く想定していないのであれば、御願いしなければならない可能性がありますね。

@yoshiokaCB さん
持ち込み前提ですか？
持ち込み前提でなければ、私の方でamidakuさんのコメントを参考に、先方と話をして必要であればこちらで判断して予約をします。

**Comment by amidaku** [comment]
ひょっとすると、音響ワゴンと映像ワゴンは一体のものを指している可能性があります。
中会議室のワゴンは大会議室のものと同じ物ですが、ワゴンの左側に音声関係の操作部が集めてあり、右側が映像関係のものがまとめられています。ワゴン前面のガラスドアの鍵で分けているのかも...
プロジェクタ自体は天井に吊ってあります。

先日OSCで中会議室を使いましたが、天井のプロジェクタはMACと相性が悪かったらしく（当方が調べた訳ではないです）、ラボの持込プロジェクタを使ってのセミナーセッションとなりました。
ラボのプロジェクタ等を持ち込むのであれば、映像ワゴンは不要です。

※
念のための話ですが、ラボの備品はラボに配備された物なので、持ち出す際には松江市さんの了解を取ってください。（同一の時刻に別イベントが使用する **可能性** もありますので）
メンバーにいらっしゃるので、おわかりになっていらっしゃると思いますが。

**Comment by yoshiokaCB** [comment]
プロジェクターはラボのものを持ち込み前提で考えてます。
スクリーンが無料で使えれば使いたいけど、スクリーンもラボのものを持ち込みでも問題ないと思います。
ラボのスクリーンとプロジェクターが使えなかったら自前のものを持ち込みしようと思っています。

> 上記備品については、懇親会費に会場費を上乗せする形（500円程度）であることも、確認の意味を込>めてこちらに付記しておきます。

上乗せでOKです！

> 音響ワゴン（1,080円）
> ワイヤレスマイク2本（1本あたり648円）

これでOKです！

こんな返答でOK？

**Comment by amidaku** [comment]
@yoshiokaCB さん、ありがとうございます。
これでFAですね！ > @Takashi-U さん

**Comment by Takashi-U** [comment]
では、松江市さんの了解をもって…

@kazuki-harada さんにご確認を御願いしてよろしいでしょうか？

**Comment by kazuki-harada** [comment]
$B$&$A$Y$5$s(B

$B:#F|(B1$BF|30$K$$$^$9$N$G(B
$BL@F|3NG'$7$^$93NG';v9`$O(B
$B%i%\$NM=Ls$NM-L5$HJ*IJ$NB_$7=P$72DH]$G$h$m$7$$$G$7$g$&$+(B

iPhone$B$+$iAw?.(B

2014/08/28 17:09$B!"(BTakashi Uchibe notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by amidaku** [comment]
「 うちべさん

今日1日外にいますので
明日確認します確認事項は」
までは解読した。

**Comment by kazuki-harada** [comment]
$B%i%\$NHwIJ;HMQ2DG=$+$r3NG'$7$^$U(B

iPhone$B$+$iAw?.(B

2014/08/28 17:09$B!"(BTakashi Uchibe notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by kazuki-harada** [comment]
MISC原田です
おはようございます。
当日のラボは予約はまだ入っていません
ラボをmatsue.rbで使用することとして抑えておくという方法はいかがでしょうか
そうすると備品も占有できます

**Comment by Takashi-U** [comment]
@kazuki-harada さん、それでは夜も占有という事で御願いしてもよろしいでしょうか？もしも必要書類などありましたら、メールいただけたら書いて送りますのでお申し付けくださいませ。

**Comment by amidaku** [comment]
どのみち、イベントが終わったら片付けにラボに入る必要がありますし、借りておきましょうよ。

**Comment by sho-h** [comment]
夜も含めて予約済みですね。あ、仮だったかもです。
- https://www.google.com/calendar/render?eid=bzBwbnI4cmdmaGlqN25ydHBhNHB1ZzFsY2MgNTYwbmhvNGcxOGE4b3NiMXVzOTY2NTVlZHNAZw&ctz=Asia/Tokyo&sf=true&output=xml

**Comment by amidaku** [comment]
橋本△
(y)

**Comment by kazuki-harada** [comment]
ラボは念のため仮状態のままになっていますね
本予約入れます
申請書は吉岡さん名で必要ですが、
こちらで作成しておきます！

**Comment by yoshiokaCB** [comment]
勝手に名前を使ってください。
氏名：吉岡隆行
団体名が必要でしたら「松江Ruby会議」とでもしておいてください。
よろしくお願いします！

**Comment by Takashi-U** [comment]
Nice!

**Comment by Takashi-U** [comment]
Matsue.rbの時に、申込み控えが来ている事をお示しして、Closeにしたいと思ってましたが、なかなか参加出来ずにすみません。
控えの封書自体は届いておりますので、進捗状況報告としてコメントさせていただきます。

**Comment by inoh** [comment]
懇親会予約の途中経過です。

**一般**
アルコールあり 12名
アルコールなし 1名

**学生**
アルコールあり 1名
アルコールなし 3名

**Comment by inoh** [comment]
懇親会予約の途中経過です。

一般
アルコールあり 19名
アルコールなし 2名

学生
アルコールあり 1名
アルコールなし 3名
キャンセル待ち 1名

とりあえず一般の目標人数の２０人に達成したのと学生のキャンセル待ちが発生している状況です。

**Comment by Takashi-U** [comment]
割合的に、アルコールの方が多いので、今回の学生さんは受け入れ可能です。

私の方で一枠増やしておきますね。

**Comment by inoh** [comment]
@Takashi-U さん
ありがとうございます！
よろしくおねがいします

**Comment by inoh** [comment]
懇親会予約の途中経過です。

一般
アルコールあり 21名
アルコールなし 5名

学生
アルコールあり 1名
アルコールなし 4名

@Takashi-U さん
とりあえず一般の枠を26名にしていたのでいっぱいになりました。
枠の拡張は可能でしたっけ？

**Comment by Takashi-U** [comment]
枠の拡張は大丈夫です。
学生ももう少し大丈夫そうです。

一般4名
学生2名

追加しておきます。

**Comment by inoh** [comment]
ありがとうございます！

**Comment by yoshiokaCB** [comment]
@Takashi-U 
当日、急遽参加したいって人の対応はどうします？
断るでOK？

**Comment by Takashi-U** [comment]
なるべくなら受け入れをと考えてます。火曜日にご挨拶へ伺うので、その時に何処までご対応いただけるかで判断します。

気持ちとしては受け入れたいですが、可能かどうか等は保留とさせて下さい、
