### ISSUE TITLE
当日スケジュールの調整

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#30]
急遽スペシャルゲストの講演が追加されるため、スケジュールの調整をしたいです。
1. まつもとさんの基調講演の後に15分程度時間を作ろうと思っています。
2. 現在本会議の終了時間が17:45となっていますが、18:00に変更したいです。
3. それに伴って懇親会の開始時間は18:45くらいにしたいです。  
   （もともと会議終了が17:45で懇親会の開始時刻が18:00で時間的に無理がありそうで気にしてました。）

募集開始後の変更で申し訳ないですが、大きな問題が無ければ、上記内容で調整したいです。
一応 12/3 に変更を決定したいと思いますので、それまでにご意見ありましたらお願いします。

@Takashi-U 
懇親会の時間変更って大丈夫でしょうか？
（会場の予約の関係とケータリングの関係）

@inoh さん @sho-h さん
またサイトの修正が入るかもしれませんが、そのときはよろしくです。

**Comment by Takashi-U** [comment]
会場につきましては、18時から22時で借りてます。念のためテルサ事務局さんに電話して、確かにこの時間帯で借りているという所確認致しました。

カプリチョーザさんにつきましては、変更依頼をしておきました。違う担当の方（Iさん）が出てこられたので、（Hさんに）伝言という形になりました。
後日確認は必要かと思いますが、時間帯が後ろに行く分には問題無いかとも思います。

ですので、懇親会担当としましては、変更を決定して頂いてOKでございます。
よろしくお願いします。

**Comment by amidaku** [comment]
えーと中継班からの要望です。
中継準備に1.5hぐらいかかりますので、当日は10:00amに入ります。
で、終わりですが、片付けに1.0hは必要です。当方懇親会には出ませんが片付けに加わっていただける方々は参加されると思いますので、そのあたりの配慮をお願いしたいです。

**Comment by yoshiokaCB** [comment]
@Takashi-U 
ありがとう！
仕事早くて助かります。

@amidaku さん
そうなんですよね。
片付けはもちろん、懇親会の準備の人はクロージング終わってからで間に合うかなど気にすることは色々ありますよね。片付けに関してはまた相談させてください。

**Comment by yoshiokaCB** [comment]
スケジュール調整完了！
