### ISSUE TITLE
スポンサーバナーの表示の乱れ

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#31]
サイトのスポンサーの表示についてですが、横幅が狭くなるとバナーの端が見切れてしまいます。
至急修正します。

**Comment by yoshiokaCB** [comment]
@sho-h さん
さっきプルリク送りました。
マージお願いします。

@inoh さん
今回は急ぎだったので、こちらで修正しちゃいました。
また次回変更お願いします！

**Comment by sho-h** [comment]
すみません。遅くなっちゃいました。反映しました。

**Comment by yoshiokaCB** [comment]
ありがとうございます！！
