### ISSUE TITLE
懇親会の領収書を作成する

### ISSUE THREAD

**Issue by Takashi-U** [matsuerb/matrk06#33]
今回の懇親会は会場費も含まれているので、運営側で領収書を発行する必要があります。

領収書の雛形は @takashi-u が作成します。
代表者は @yoshiokaCB さん、組織名は「松江Ruby会議06 実行委員会」でよろしいでしょうか？

**Comment by yoshiokaCB** [comment]
特に他から意見がなければ、それでOKです。

ちなみにここで作ろうかと思ってました。
https://xn--lorw95b519a.net/

まぁ、細かいことはプロにお任せします。
自分はハンコウつけばOK？
必要なら印刷するよ。

**Comment by amidaku** [comment]
SITWもJAWSも僕がやるイベントは全部それでやってますよ。

**Comment by Takashi-U** [comment]
早速にありがとうございます。
では、本件につきましては私が取りまとめます。

詳細については個別にご連絡させていただき、こちらには進捗を記載していきますね。

**Comment by yoshiokaCB** [comment]
とりあえず終わったのでcloseします。
