### ISSUE TITLE
講演の参加者人数について

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk06#34]
Doorkeeperでの問い合わせですが当日飛び入りで５名程度参加が可能かとメッセージがありました。
- 特に人数制限は設けない  
- 席が足りない場合は立ってみる

でよかったですよね？

**Comment by inoh** [comment]
ちなみに現在のDoorkeeperでの講演のエントリ数は41名で55名の制限にはしてあります。

**Comment by yoshiokaCB** [comment]
45人で申し込みは終了しました。
当日、申し込み無しで来られた人は「立ち見になります」とお伝えしてご案内する予定です。
