### ISSUE TITLE
レポート班の人員配置

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#35]
@sho-h さん

自分の把握してる人は以下の人ですが、セッションごとの割り振りは大丈夫でしょうか？

> 橋本さん、西田さん、佐田さん、本多さん、槙原さん、井上さん、小嵜さん

それと小嵜さんは仕事の都合で当日欠席とのご連絡をいただいてます。
レポートの人員補給が必要ですか？

**Comment by AyakoMakihara** [comment]
@sho-h 受付・写真撮影を兼ねてますし、初めての参加なのでレポート班は難しいと思います。御調整頂きたいです！

**Comment by nishidayuya** [comment]
http://matsue.rubyist.net/matrk06/#program

そうすると，橋本さん，佐田さん，本多さん，井上さん，西田 の5名で以下を担当する形でしょうか．

```
内容 | 担当
---- | ----
基調講演 | 
ショートセッション | 
ライブコーディング大喜利 | 
ゲスト講演 | 
講演1 | 
講演2 | 
講演3 | 
```

**Comment by sho-h** [comment]
@yoshiokaCB さん、ありがとうございます。忘れてました...5人居れば最大2人が2つまでやればいいので割と例年通りかなと思いますのでおそらく大丈夫です。

@AyakoMakihara さん、了解ですー。

@inoh さん、 @nishidayuya さんが挙げてくれたものでどれ希望とかあります？それ以外は月曜以降にでもえいやっと決めちゃおうかと思います。

**Comment by inoh** [comment]
私はライブコーディング大喜利以外であればどこでもよいですよー。
初めてのレポートなので実際書くときまたご支援ください！

**Comment by sho-h** [comment]
@inoh さん、了解です。じゃあ、パネルディスカッションをお願いさせてください。

以下の担当になるように相談しました。

```
内容 | 担当
---- | ----
基調講演 | 本多さん
ショートセッション | 西田さん
ライブコーディング大喜利 | 西田さん、佐田さん
ゲスト講演 | 橋本
講演1 | 佐田さん
講演2 | 井上さん
講演3 | 西田さん
```

という事でcloseします。
