### ISSUE TITLE
当日の写真撮影について

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#36]
@KatoAtsue さん

当日の写真撮影についてですが、以下の人たちが当日写真撮影をしてくれる予定です。

@AyakoMakihara さん
@inoh さん
@tomo-k さん

撮影した写真をどうやって加藤さんに送るかなどスタート前に確認しておいてもらえると良いかもしれません。
あと、各セッションで撮影漏れがないよう、簡単な担当を決めをされてると良いかもしれません。

**Comment by AyakoMakihara** [comment]
了解しました！ :ok_woman:

**Comment by KatoAtsue** [comment]
了解です。どうもありがとうございます。

**Comment by KatoAtsue** [comment]
当日写真撮影をしていただいた方は、Flickrまたはストレージサービスなどにアップロードしていただき、URLをこのイシューかメールで教えていただけますでしょうか。
他にも良い方法があったらお知らせください。
また、吉岡さんの講演「Matsue.rbのふりかえり - 2014 -」の時、どなたかに撮影していただけると助かります。
よろしくお願いします。

**Comment by AyakoMakihara** [comment]
@inoh さんがRuby会議用にfbグループを作成してくれたので、こちらのアルバム作成で管理する事になりました。メモとして記載しておきます :memo:

**Comment by takaokouji** [comment]
_ちょっとこれは私と吉岡さんの考えなので相談が必要なのですが_、各セッションで2枚程度の写真を公式サイトにアップロードすることを想定しています。また、サイズは400x300ピクセルとか、800x600ピクセル程度を想定しています。

それ以外のものは、オフィシャルではなくて、個人的に撮影していただいたものとして、それぞれのFlickrなどのウェブサービスで公開していただくとありがたいですね :sweat_smile: 
(実は、いろいろなウェブサービスの認証が厳しくなってきており、一人が複数のアカウント取得するのは難しくなってきています)

なにがいいたいかといいますと、写真撮影の担当の方で、Facebookのアルバム機能などを利用してベストショットを選考するところまでやっていただけないでしょうかね。決まったタイミングで、ウェブ担当の方にアップロードしていただく想定です。
あと、当日はたくさんの枚数を撮影してただくと思いますが、ほんの少し採用されないかもしれません。ごめんなさい :bow:

**Comment by sho-h** [comment]
関連する発言：https://github.com/matsuerb/matrk06/issues/27#issuecomment-67439559

**Comment by takaokouji** [comment]
すみません、 #27 にて松江Ruby会議06としてどのように公開するのか議論している最中でして、

> なにがいいたいかといいますと、写真撮影の担当の方で、Facebookのアルバム機能などを利用してベストショットを選考するところまでやっていただけないでしょうかね。決まったタイミングで、ウェブ担当の方にアップロードしていただく想定です。
> あと、当日はたくさんの枚数を撮影してただくと思いますが、ほんの少し採用されないかもしれません。ごめんなさい :bow:

の部分は確定ではないです。
写真担当の方、お手数ですが #27 もご確認いただき、よろしければご意見ください :bow:

**Comment by inoh** [comment]
担当たたき台

撮影する場面

| 場面 | 講演者 | 担当 |
| :-- | :-- | :-- |
| 開会あいさつ | 吉岡さん | 井上 |
| 基調講演 | まつもとさん | 井上 |
| ショートセッション | 笹田さん | 加藤さん |
| ライブコーディング大喜利 | 多数 | 加藤さん |
| ゲスト講演 | 倉貫さん | 木村さん |
| Matsue.rbのふりかえり - 2014 - | 吉岡さん | 木村さん |
| パネルディスカッション | 高尾さん | 槇原さん |
| スモウルビーでライブコーディング | 本多さん | 槇原さん |
| クロージング | 吉岡さん | 井上 |

**Comment by yoshiokaCB** [comment]
無事に撮影が終わってますので、クローズします。
