### ISSUE TITLE
懇親会の受付・設営係を決める

### ISSUE THREAD

**Issue by Takashi-U** [matsuerb/matrk06#37]
懇親会の受付係と設営係（兼務）を決めさせてください。

懇親会の設営については、カプリチョーザさんが基本的には行います（料理等の配置）が、LTのスペース確保と椅子等の配置を確認して、必要があれば多少動かす程度の軽作業です。（5分程度）

設営の後は受付係をそのままの流れで行います。

3名必要の見込みです。そのうち一人は @Takashi-U が行います。

**Comment by Takashi-U** [comment]
1名はゆんさんにご協力いただける事になりました。

**Comment by kazuki-harada** [comment]
$B86ED<uIU$d$j$^$9$h$s!*(B

iPhone$B$+$iAw?.(B

2014/12/13 17:13$B!"(BTakashi Uchibe notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by Takashi-U** [comment]
もう一回お願いします〜

**Comment by kazuki-harada** [comment]
失礼、再投稿。
原田やります一

**Comment by Takashi-U** [comment]
ありがとうございます！
予定人数に達したのでクローズします。

よろしくお願いします！

**Comment by Takashi-U** [comment]
Close後に失礼します。
当日に必要な作業等が発生しておりまして、僭越ながら個別にお声がけさせていただき、担当者を追加させていただきました。

会場の設営につきまして、RailsGirlsMatsueのオーガナイザーお二人にお願いしました。（快諾ありがとうございます！）

会場の椅子や机の配置といったところは、打ち合わせの上お二人にお任せしたいと思っております。（もちろん、私も設営として一緒に作業できる限りがんばります。）

受付のお二人と設営のお二人、うちべっこ。の体制でございますが、当日の状況によってはお手伝いをお願いするお声がけするような事も有ろうかと存じます。その際には何卒よろしくお願い申し上げます。

**Comment by yoshiokaCB** [comment]
明日初めのミーティングで話をふるので皆さんに簡単に説明してもらってもよい？
