### ISSUE TITLE
本編の受付について

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#38]
@AyakoMakihara さん　@kaorimatsuokaさん　原田さん　石原さん

以下、当日の受付について、注意事項です。
ご一読ください。
また、何か他にありましたらこちらのissueに書き出しておいてもらえると助かります。
- 当日の受付は13時くらいから開始したいと思います。
- 受付時に懇親会に参加される方から参加費も集めておいてください。  
  （集めたお金は持ってるのが不安なら @Takashi-U or @yoshiokaCB に預けてください。）
- 領収書は @Takashi-U さんが準備します。
- 参加者リストは @inoh さんか @Takashi-U さんが準備します。
- 参加申し込みなしで来場された方に関しては参加者リストに名前を書いてもらってください。  
  （定員はいっぱいですが、とりあえず入場してもらう方向で対応をお願いします。）
- 受付が終わった人には、人数が多くて込んでいることを伝え、前の方から座ってもらうように促してください。

**Comment by Takashi-U** [comment]
この辺りお話をしていませんでしたが、思うところありますので懇親会の受付は自分にやらせてください。その補助をどなたかお一人にお願いしたいところです。

このIssueができる前までは、懇親会の会場にて集金をするものかと思っておりました。失礼しました。
私を含めると受付5名という事になります。多すぎるのか適切かはわかりませんが…

**Comment by yoshiokaCB** [comment]
@Takashi-U 
了解っす。よろしくお願いします。
5人は多分受付に立てないので、入れ替わりで受付とかにしたらいいですかね？
細かいところは皆さんにお任せします。

**Comment by Takashi-U** [comment]
ありがとうございます！

**Comment by AyakoMakihara** [comment]
@Takashi-U 写真撮影可能かどうか、受付でお聞きしていた方が良いでしょうか？また、ＮＧの方には何かわかる目印（シール）など、ご配慮が必要かどうか教えてください。

**Comment by yoshiokaCB** [comment]
聞いてもらうの良いですね！！
一応最初の挨拶で撮影されたら困る人って聞こうと思ってましたが、受付で聞いて目印あるとより確実ですよね。

**Comment by Takashi-U** [comment]
ご指名いただいたのに遅くなってすみません。

名札等の何かアイテムが必要になりますが、その点どうでしょうか？

@yoshiokaCB さん、僕が知らないだけだったらすみません。名札等の設えは予定されてますでしょうか？

**Comment by yoshiokaCB** [comment]
名札などは使用しない方向で考えてました。
今から名札を準備するのもちょっと大変そうですよね。

「顔をアップで写したりはしないので、写真に少し写り込んだりしても大丈夫ですか？」とか聞き方すれば、大体OKもらえるんじゃないですかね？
それか、オープニングでも聞くので、そこで手を上げる人は撮影者がしっかり覚えとくとかどうですかね？

**Comment by Takashi-U** [comment]
ガッテンです。数が少ない見込みなので、臨機の対応という事で理解しました。

**Comment by AyakoMakihara** [comment]
では、受付で写真の件はご確認させて頂きます :ok:

**Comment by KaoriMatsuoka** [comment]
@Takashi-U 
つり銭を用意してます。
私は他に役割ないですし、受付補助しますよ。交代するほどの作業量もないですし。

**Comment by yoshiokaCB** [comment]
お金関係、書類関係のやり取りが終わりましたらcloseしたいと思います。

**Comment by sho-h** [comment]
参加人数わかったら #40 に対応するので教えてくださいー。

**Comment by yoshiokaCB** [comment]
了解っす！

**Comment by yoshiokaCB** [comment]
来場者数はトータルで57人でした！

**Comment by sho-h** [comment]
おぉ、早速ありがとうございます！

**Comment by yoshiokaCB** [comment]
無事に本編を終えましたので、クローズします。
