### ISSUE TITLE
当日の会場準備手伝いについて

### ISSUE THREAD

**Issue by yoshiokaCB** [matsuerb/matrk06#39]
皆さんにお願いです。

当日、参加人数が50名を超えています。
なので、会場を出来るだけ広く使うために机を別の場所に移動します。
移動させる作業のお手伝い募集します。
来れる人は11時くらいにラボに来てください。
来れる人ここで意思表明お願いします。
人数少ないようでしたら個別にお声がけさせてもらいます。

**Comment by Takashi-U** [comment]
概ねその時間に行けます。多分間に合うと思いますが、遅れてもそんなには遅れないです。

**Comment by takaokouji** [comment]
行きます！

2014年12月18日木曜日、Takayuki Yoshiokanotifications@github.comさんは書きました:

> 皆さんにお願いです。
> 
> 当日、参加人数が50名を超えています。
> なので、会場を出来るだけ広く使うために机を別の場所に移動します。
> 移動させる作業のお手伝い募集します。
> 来れる人は11時くらいにラボに来てください。
> 来れる人ここで意思表明お願いします。
> 人数少ないようでしたら個別にお声がけさせてもらいます。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/matsuerb/matrk06/issues/39.

## 

Kouji Takao kouji.takao@gmail.com

**Comment by sho-h** [comment]
( ﾟдﾟ)ﾉ

**Comment by Takashi-U** [comment]
@takaokouji さん、 @sho-h さん、当日は名刺を忘れずに･･･

**Comment by sho-h** [comment]
ぼ、僕は常にカヴァンに入ってますよ...(枚数を確認しとかなくちゃ

**Comment by nishidayuya** [comment]
来ます!

**Comment by sho-h** [comment]
そういえば何名くらいいると大丈夫です？必要ならもう1人くらい近くにいる人に声かけれます。

**Comment by amidaku** [comment]
僕と土井さんはもう少し早めに入りますが、中継準備の方で手が離せないと思います。
机移動等のお手伝いできないと思います。
また、 @rockzero は部活終わってから移動してくるので作業の方は難しいと思います。
よろしくお願いします。

**Comment by yoshiokaCB** [comment]
@sho-h さん
嬉しいです！
ここに参加表明してもらってください。
あんまり多くいても手持ち無沙汰になるので、ここでの表明は5人くらいかと思ってます。
（表明されてないけど倉橋さんが来られるはず。）
基本机を別の場所に移動すること以外特にやることないので。
なので、今のところ
1. うちべっこ。
2. 高尾さん
3. 橋本さん
4. 西田さん

あと、一人のくらいですかね。
そこに吉岡と倉橋さんを足してトータル7人も集まれば十分かなと。

@amidaku さん
了解っす。だいたい事情は知ってますんで、大丈夫です！

**Comment by yoshiokaCB** [comment]
参加表明してもらったらクローズします。

**Comment by ToruKurahashi** [comment]
這ってでも行きます。

**Comment by sho-h** [comment]
@sada くんに声を掛けてOKをもらいました！

**Comment by yoshiokaCB** [comment]
はい。ありがとうございます。
集まらなかったら真っ先に声がけさせていただく予定の人でした。
空気読んでいただきありがとうございます！

**Comment by takaokouji** [comment]
すみません、家族が体調を崩しまして(^^;;
明日は12:30くらいには行きたいと思いますが、ちょっとわからないですm(_ _)m

## 

Kouji Takao kouji.takao@gmail.com
