### ISSUE TITLE
matrk06の公式サイトの空を作る

### ISSUE THREAD

**Issue by inoh** [matsuerb/matrk06#4]

**Comment by inoh** [comment]
とりあえず前回のホームページ（matrk05）を今回のホームページに（matrk06）にコピーしました。
プルリクエストを送ったので問題なければ取り込みます。

https://github.com/matsuerb/matsuerb-nanoc/pull/173

@nobyuki @sada @eijik
取り込んだら各々気づいた点修正してください！
よろしくお願いします。

**Comment by sho-h** [comment]
公式サイトへの反映は作業が進むまでは matrk06 以下だけ除外して push しようと思うのでいつでもマージしてもらって大丈夫です。:)

また、[matsuerb-nanoc/README.md](https://github.com/matsuerb/matsuerb-nanoc/blob/master/README.md)にも公式サイトに反映させる手順を追記しました！

**Comment by inoh** [comment]
@sho-h さん
返信遅くなりましたが諸々ありがとうざいます！
ここ２週間くらいパソコン調子が悪くて（継続中ですが、、、）少しづつ修正開始します！

**Comment by inoh** [comment]
きたる9/20の一般公募に向けて載せる内容について整理が必要になってきました。
今私が把握している整理内容は下記の通りです。
- 開催時間の決定
- 外向きの目的の決定
- プログラム内容の決定
- お問い合わせ先の決定
- 昼食場所と懇親会の場所確保
- 場所確保を受けてのdoorkeeperを確保

ざっとこんな感じに思っています。
もし内容が決まっているところがあれば情報をご提供いただけると助かります。
よろしくお願いします。

**Comment by yoshiokaCB** [comment]
@inoh さん
色々とありがとうございます！

> 開催時間の決定
> プログラム内容の決定

こちらを参考にしてください。
https://github.com/matsuerb/matrk06/wiki/%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%EF%BC%88%E5%BD%93%E6%97%A5%EF%BC%89

> お問い合わせ先の決定
> 外向きの目的の決定

ちょいと相談です。

> 昼食場所と懇親会の場所確保
> 場所確保を受けてのdoorkeeperを確保

こちらを参考にしてください。
https://github.com/matsuerb/matrk06/issues/3

**Comment by inoh** [comment]
@yoshiokaCB さん
情報ありがとうございます！
書ける範囲でページ手直ししてまた連絡します！

**Comment by inoh** [comment]
とりあえず私が拾った範囲で下記の通りホームページに反映させました。
プルリクエスト：https://github.com/matsuerb/matsuerb-nanoc/pull/183
- 開催時間の決定
  - 開催：13:00 - 17:45
  - 懇親会：18:00 -
- 外向きの目的の決定
  - とりあえず内向きの目的を少し加工して載せています
  - また相談させてください！
- プログラム内容の決定
  - 大枠として「基調講演」「ライブコーディング大喜利」「講演（20分 x 5枠）」という認識です
  - 詳しい詳細が決まり次第随時更新予定です
- お問い合わせ先の決定
  - 「matsuerubykaigi06@googlegroups.com」で確保しました
- 懇親会の場所確保
  - 参考）https://github.com/matsuerb/matrk06/labels/%E6%87%87%E8%A6%AA%E4%BC%9A
  - 場所や値段設定が正式決定したらまた教えてください
  - 詳細な内容についてはホームページではなくてdoorkeeperに載せる予定です
- 場所確保を受けてのdoorkeeperを確保
  - @nobyuki とりあえずのたたき台としてアカウントの確保と柄作成をしていただけるとうれしいです
