### ISSUE TITLE
公式サイト/scheduleの更新

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk06#40]
以下を更新する。
- 参加受付中→終了(6X名参加)
- リンク先にUstやTogetter(その時にあれば)を追加
- matrk06のページも終了にしてしまう(メールの問い合わせ先も削除)

**Comment by amidaku** [comment]
昨日は、お疲れ様でした。
Ustですが、一月程度で録画は削除されるので、uri載っけるのはやめといたほうが良いと思います。
そのうちセッション毎に分割した録画をYoutubeで公開する予定ですが、公開するまでuriが、決まらないので…

**Comment by sho-h** [comment]
そういえばそうでしたね > ust。ではYoutubeを待ちます。
togetterは http://togetter.com/li/760234 を作っていただいたので発言の過不足を確認してこれを載せようかと考えています。(なにか気になる事があれば教えてください)

**Comment by sho-h** [comment]
残り作業である #42 は分けてこちらは close。
