### ISSUE TITLE
レポート作成

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk06#41]
以下のような流れを考えています。
- LTの担当を決めてなかったのでLTも決める
  - @inoh さんどうでしょうと声をかける予定
- どこで作成するか相談する
  - 05と同じならGoogleGroup
- #35 とLTの担当に従って作成する
- [ドキュメント](https://github.com/ruby-no-kai/official/wiki/RegionalrubykaigiRubimaReport)にそって、[るびまレポジトリ](https://github.com/rubima/rubima)にプルリクする

**Comment by inoh** [comment]
今日はお疲れさまでした。
私担当のセッションが中止になって油断してました。
懇親会のときの録画とかないですよね？
LTの話をきちんと聞いてなかったので覚えてたり覚えてなかったり

**Comment by sho-h** [comment]
録画はないんでしたよね...(僕も不確かです)。じゃあ、LTは全員で作るか簡単なものにするかといったところですね。

**Comment by amidaku** [comment]
中継班は二人とも都合により懇親会参加できなかったので録画無いです。
申し訳ないです。ごめんなさい。

**Comment by sho-h** [comment]
録画ない了解ですー。

どこで作成するかについてGoogleGroupで特に問題ないようであれば、以下と同じ修正を公式サイトにしておきます。
- https://github.com/matsuerb/matsuerb-nanoc/commit/3314202e1775bcc6d625908a2eafcd22fbe3fb73

**Comment by nishidayuya** [comment]
前例だとLTはタイトルの紹介に留めているようです．https://github.com/matsuerb/matrk05/issues/1

とはいえ，自分はタイトルすら記録してなかったので思い出さないといけないわけですが... タイトルぐらいつぶやいておけばよかった． :sweat_smile:

**Comment by nishidayuya** [comment]
レポート作成にあたって参考になるURIを挙げておきます．

前回: https://github.com/matsuerb/matrk05/issues/20

過去のレポート:
- http://magazine.rubyist.net/?0040-MatsueRubyKaigi04Report
- http://magazine.rubyist.net/?0035-MatsueRubyKaigi03Report
- http://magazine.rubyist.net/?0034-MatsueRubyKaigi02Report

**Comment by sho-h** [comment]
URLあざます！タイトルは最悪ご本人さん達にお聞きするとして、#19 を参考にするに以下のみなさんに発表いただいた感じですかね？
- 五十嵐さん(本編): 永田町に届けられるサービスTmix
  - https://speakerdeck.com/igaiga/matrk06-tmix
- 五十嵐さん(懇親会): 松江のいいところ
  - https://speakerdeck.com/igaiga/matrk06-lt
- 笹田さん(懇親会): Ruby 2.2の紹介(タイトルTODO)
- 杉原さん
- 後藤さん

**Comment by yoshiokaCB** [comment]
えーと、あと槙原さんもLTされましたよ。
槙原さん、杉原さん、後藤さんのLTタイトルはお聞きしておきますね。
話された内容は何となく覚えてるけど、タイトルまでは記憶してません（汗）

**Comment by sho-h** [comment]
@yoshiokaCB さん、ありがとうございます！！よろしくお願いします！あれ、そういえばペッパーくんの話し、Togetterになかったです？(TODO要確認、載ってる方がいい場合もあると思うので必要であればツイートを探して追加してもらう)

あと、本編で中止になったセッションは懇親会でやったとかありました？

**Comment by sho-h** [comment]
上記TODOについてはやはりないようでしたが、みつけれたつぶやきも以下ともう一個くらいだったので、残念ながら追加は難しそうですね...
- https://twitter.com/yotii23/status/546246800634437632

**Comment by yoshiokaCB** [comment]
本編で中止になって懇親会でしたのは、

<pre>
パネルディスカッション 
タイトル：「来て、見て、感じた、日本、松江、Ruby、NaCl」
発表者：正レナト 氏、多根チアゴ 氏、高尾コウジ 氏（司会・進行）
</pre>

です。

とりあえず、失礼のないように以下の方々のタイトルだけ聞いてここに記しておきますね。

> 槙原さん、杉原さん、後藤さん

**Comment by yoshiokaCB** [comment]
タイトルは以下のようになります。

## 

### 「僕らが東京で学んだこと」
- 杉原さん

## 

### 「感情認識ロボットPepper、ようこそ島根県へ♪」
- 槇原さん

## 

### 「新たなプログラミングスタイルの確立を目指して」
- 後藤さん

**Comment by yoshiokaCB** [comment]
ちなみに後藤さんはスライドもアップされてて、urlを教えてもらいました。

http://www.slideshare.net/gototgz/ruby-20141220

**Comment by sho-h** [comment]
@yoshiokaCB さん、ありがとうございました。助かります。

とりいそぎ、[report以下](https://github.com/matsuerb/matrk06/blob/master/report/matsuerubykaigi06-template.hiki) にテンプレートを作ってみました。中身を入れるのは Google Groupとかを考えていますが、どうせGitHubでプルリクするのでそのままここでやってもいいかもな感もあったりします。

その辺はまた別途。みなさま忘れないうちに担当分をよろしくお願いしますー。m(_ _)m

**Comment by sho-h** [comment]
WIPです。自分の担当＋懸念事項を解決したので、正座して待ってる。

**Comment by sho-h** [comment]
次の号(50号)の締め切りが決まったみたいです。50号に出すためには3/15締め切りになりました。(目次とアウトラインは以前のテンプレートを出す感じにしようかと。
- 2/15 (日) 記事申込、概要の締切
- 3/1 (日) 記事の目次、アウトライン締切
- 3/15 (日) 記事の締切
- 3/29 (日) 校正完了、リリース

無理そうなら51号にまわしてもらうので、2月の定例会で相談したいですね。

**Comment by sho-h** [comment]
画像貼ったりなどしたあと、引き続き正座して待ってる！

```
　 ∧＿∧
　（　・∀・） ﾄﾞｷﾄﾞｷ
　（　∪ ∪
　と＿_）__）
```

**Comment by sho-h** [comment]
2月の定例会で相談して51号にまわしてもらう事にしました。

**Comment by sho-h** [comment]
51号は8月頃らしいので、7月には終えたいとすると後1月ほどでござる。

**Comment by yoshiokaCB** [comment]
@sho-h さん
すみません。ずっと放置でした(^^;;)
あと、何人くらいですかね。。。
こちらから催促しましょうか？

**Comment by sho-h** [comment]
@yoshiokaCB さんどもです。あと1人か2人分だったはずですね。とりあえず今月の定例会で相談してみようかと思っています。52号なら52号でも僕は別にいいかなと思ってます。

**Comment by yoshiokaCB** [comment]
@sho-h さん
了解っす。今月自分は定例会に出れないので、すみませんが、よろしくお願いします！
まぁ、自分も何号でも構いませんが、せっかくの機会なので進めちゃいましょう！！

**Comment by sho-h** [comment]
現状ですが提出までdoneです。(9月までにできた！)

51号に掲載いただく流れで進んでいます。

**Comment by sho-h** [comment]
るびまチームさんの校正まで終わったのでcloseします。

**Comment by amidaku** [comment]
どこに報告上げるべきか迷いましたが、クローズされているこのトビにw

なんとか07開催までに前回開催の動画をUPできました。ﾊｱﾊｱ。

基調講演
https://youtu.be/XUdS8RYWL3g

ショートセッション
https://youtu.be/1mobbUMKZ8k

ライヴコーディング大喜利
https://youtu.be/7g0rWpJ7r7s

ゲスト講演
https://youtu.be/UlVdKi-YVtM

Matsue.rb 2014ふりかえり
https://youtu.be/Fz8wNh8VcV4

スモウルビーでライブコーディング
https://youtu.be/TTn5d-8OmZ8

大変遅くなり、申し訳ございませんでした。
やっと私の06が終了しました。
07もよろしくお願いします。

**Comment by sho-h** [comment]
お疲れさまです！これって再生リストとかそういうので06分のみ一覧が見れたりできます？

**Comment by amidaku** [comment]
一応 matrk06 タグつけてるけど、検索はGoogle任せに

**Comment by amidaku** [comment]
(途中で切れた…

uriも検索もGoogle任せになるので、06分だけの表示は難しいです。
仮に出来ても、いつもその結果になる保証は無いです。

なので、先日のコメントでuriまとめて書きました。

**Comment by sho-h** [comment]
了解っす！ http://matsue.rubyist.net/schedule/ へのリンクをどうはろうかなと思ったんですが、じゃあ、なるべく短く全部のリンクを作ろうと思ったら、一行で中継 1 2 3 4 5...みたいな感じがいいかもですねと思ったのでとりあえず、来月とかそうします。

**Comment by amidaku** [comment]
知らなかったけど、こんな事ができたので、かなり今更ですがこっそり報告。
https://www.youtube.com/playlist?list=PLbJxhePIoIPDCF_KeFc-U5W4XdmTYWPVd

**Comment by sho-h** [comment]
どもです。http://matsue.rubyist.net/schedule/#section-2 を更新しました。

**Comment by yoshiokaCB** [comment]
@amidaku さん
ありがとうございます。
画質も結構いいですね！
なんか自分が写ってるの改めて見ると恥ずかしいですね(^^;;)
