### ISSUE TITLE
アンケート集計

### ISSUE THREAD

**Issue by sho-h** [matsuerb/matrk06#43]
アンケートの集計は行う予定とかあるんでしたっけ？的なIssue。

**Comment by yoshiokaCB** [comment]
はい。
預かってますんで、どこかにアップしたいです！
今のところ、開催報告と一緒にMatsue.rbにあげたいですがどうですかね？

**Comment by sho-h** [comment]
おぉ、いいですね。:)

**Comment by sho-h** [comment]
まぁもういいかなどと思ったのでcloseしてしまいます。
